version: "3.9"

services:
  ditm:
    image: jonathanarns/ditm
    container_name: ditm
    hostname: ditm
    environment:
      CONTAINER_HOST_NAMES: etcd1,etcd2,etcd3
    volumes:
      - ./volumes/volumes:/volumes:z
      - ./volumes/recordings:/recordings:Z
      - ./volumes/snapshots:/snapshots:Z
    ports:
      - "8000:80"
      - "5000:5000"
    depends_on:
      - etcd1
      - etcd2
      - etcd3

  
  etcd1:
    image: op-etcd
    container_name: etcd1
    hostname: etcd1
    ports:
      - 8081:8080
    environment: 
      - HTTP_PROXY=ditm:5000
      - PID=1
      - PEERS=2,3
      - PEER_DOMAINS=etcd2:8080,etcd3:8080

  etcd2:
    image: op-etcd
    container_name: etcd2
    hostname: etcd2
    ports:
      - 8082:8080
    environment: 
      - HTTP_PROXY=ditm:5000
      - PID=2
      - PEERS=1,3
      - PEER_DOMAINS=etcd1:8080,etcd3:8080

  etcd3:
    image: op-etcd
    container_name: etcd3
    hostname: etcd3
    ports:
      - 8083:8080
    environment: 
      - HTTP_PROXY=ditm:5000
      - PID=3
      - PEERS=1,2
      - PEER_DOMAINS=etcd1:8080,etcd2:8080
